export const GET_POSTS = "GET_POSTS";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const ENABLE_POSTS_IS_FETCHING = "ENABLE_POSTS_IS_FETCHING";
export const DISABLE_POSTS_IS_FETCHING = "DISABLE_POSTS_IS_FETCHING";
export const ADD_NEW_POST = "ADD_NEW_POST";
export const SET_POST_ERROR = "SET_POST_ERROR";
export const SET_PAGE = "SET_PAGE";
