export const USER_ACTION_TYPES = {
  GET_USER: 'GET_USER',
  POST_USER: 'POST_USER',
  UPDATE_USER: 'UPDATE_USER',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  TOGGLE_LOGOUT: 'TOGGLE_LOGOUT',
};

export const USERS_ACTION_TYPES = {
  GET_USERS: 'GET_USERS',
  POST_USERS: 'POST_USERS',
  ENABLE_USERS_ISFETCHING: 'ENABLE_USERS_ISFETCHING',
  DISABLE_USERS_ISFETCHING: 'DISABLE_USERS_ISFETCHING',
};

export const POSTS_ACTION_TYPES = {
  GET_POSTS: 'GET_POSTS',
  UPLOAD_POSTS: 'UPLOAD_POSTS',
  ENABLE_POSTS_ISFETCHING: 'ENABLE_POSTS_ISFETCHING',
  DISABLE_POSTS_ISFETCHING: 'DISABLE_POSTS_ISFETCHING',
};
