export const USER_ACTION_TYPES = {
  GET_USER: 'GET_USER',
  POST_USER: 'POST_USER',
  UPDATE_USER: 'UPDATE_USER',
  TOGGLE_LOGIN: 'TOGGLE_LOGIN',
  TOGGLE_LOGOUT: 'TOGGLE_LOGOUT',
};

export const USERS_ACTION_TYPES = {
  GET_USERS: 'GET_USERS',
  POST_USERS: 'POST_USERS',
  ENABLE_ISFETCHING: 'ENABLE_ISFETCHING',
  DISABLE_ISFETCHING: 'DISABLE_ISFETCHING',
};
