export const GET_USERS = "GET_USERS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const ADD_USER = "ADD_USER";
export const DELETE_USER = "DELETE_USER";
export const ENABLE_USERS_IS_FETCHING = "ENABLE_USERS_IS_FETCHING";
export const DISABLE_USERS_IS_FETCHING = "DISABLE_USERS_IS_FETCHING";
export const SET_USERS_ERROR = "SET_USERS_ERROR";